# Simple workflow for deploying prerendered Angular app to GitHub Pages
name: Deploy Angular Prerendered App to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Change to the 'cv' folder before installing dependencies
      - name: Install Dependencies
        working-directory: ./cv # Specify the working directory as 'cv'
        run: |
          npm install -g @angular/cli
          npm ci

      # Step 3: Build Angular app with prerendering
      - name: Build Static Prerendered Files
        working-directory: ./cv # Continue working inside 'cv' folder
        run: npm run build-gh

      # Step 4: Upload the prerendered files (cv\dist\cv\browser) as artifacts for deployment
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './cv/dist/cv/browser'

      # Step 5: Deploy the uploaded artifacts to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
